version: '3'
services:
        dbos:
                image: mysql:5.7
                volumes:
                        - new_volume1:/var/lib/mysql
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: rootpass
                        MYSQL_USER: nikita
                        MYSQL_PASSWORD: redhat
                        MYSQL_DATABASE: mydb

       

        
        wordpressos:
                image: wordpress:5.1.1-php7.3-apache
                restart: always
                depends_on: 
                    - dbos
                ports:
                    - 8080:80
                environment:
                          WORDPRESS_DB_HOST: dbos
                          WORDPRESS_DB_USER: nikita
                          WORDPRESS_DB_PASSWORD: redhat
                          WORDPRESS_DB_NAME: mydb
                volumes:
                        - new_volume2:/var/www/html
volumes:
        new_volume1:
        new_volume2:

